// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhwhdafrizmskrxrbycx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRod2hkYWZyaXptc2tyeHJieWN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTY5NjQsImV4cCI6MjA1OTU5Mjk2NH0.MUCDYYvAUk8L-A4srCnUnVQL_ZkOrlMiFpBAPrHl28Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);